// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTbUserAuth = "user"

// User mapped from table <tb_user_auth>
type User struct {
	ID       int    `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Username string `gorm:"column:username;type:varchar(50);not null;uniqueIndex:username,priority:1" json:"username"` // 用户名
	Password string `gorm:"column:password;type:varchar(100);not null" json:"password"`                                // 密码
}

// TableName User's table name
func (m *User) TableName() string {
	return TableNameTbUserAuth
}

func (m *User) IsValid() bool {
	if m.Username == "" {
		return false
	}

	if len(m.Password) < 4 || len(m.Password) > 16 {
		return false
	}

	return true
}
